<?php

include_once("./Services/Repository/classes/class.ilObjectPlugin.php");

/**
 * Class ilObjDhbwTraining
 *
 * @author: Benjamin Seglias   <bs@studer-raimann.ch>
 */

class ilObjDhbwTraining extends ilObjectPlugin {


	/**
	 * Constructor
	 *
	 * @access        public
	 *
	 * @param int $a_ref_id
	 */
	public function __construct($a_ref_id = 0) {
		parent::__construct($a_ref_id);
	}


	protected function initType() {
		$this->setType(ilDhbwTrainingPlugin::PLUGIN_PREFIX);
	}


	public function doCreate() {
		parent::doCreate(); // TODO: Change the autogenerated stub
	}


	public function doRead() {
		parent::doRead(); // TODO: Change the autogenerated stub
	}


	public function doUpdate() {
		parent::doUpdate(); // TODO: Change the autogenerated stub
	}


	public function doDelete() {
		parent::doDelete(); // TODO: Change the autogenerated stub
	}


	/**
	 * @param ilObjDhbwTraining $new_obj Instance of
	 * @param int                   $a_target_id obj_id of the new created object
	 * @param int                   $a_copy_id
	 *
	 * @return bool|void
	 */
	public function doCloneObject($new_obj, $a_target_id, $a_copy_id = NULL) {
		assert(is_a($new_obj, ilObjAssistedExercise::class));
	}
}